Add EOL option.
catdad/eol-fix-stream pull request #1
Opened 2021-08-18 21:09 UTC by btimby

- Caller can now specify desired EOL sequence: `'\r'`, `'\n'` or `'\r\n'`.
 - Simplify implementation.

2021-08-18 21:22 UTC, btimby commented
@catdad Thanks for the library. I will mention my use-case. I have an FTP server written for node, and I need to implement ASCII file transfer mode. In that mode, the server must convert from `CRLF` to `LF`. Then on download, it must convert from `LF` to `CRLF`. The library as it stood allowed for the former, but not the latter.

BTW, I reviewed all the libraries on npm that I could find for this task and they were all broken or overly complex. I may have some additional PRs once I integrate this into my codebase, I am working with file and socket streams there.

2021-08-19 11:32 UTC, catdad commented
Thanks for submitting this PR!

In the description you say that you "simplify implementation", but that doesn't really give me information about what you changed and why you changed it. Can you describe the simplifications you made and why they were made, please?

2021-08-19 12:05 UTC, catdad requested changes

2021-08-19 12:05 UTC, catdad commented on index.js
> +module.exports = function lfcrClean(eol='\n') {
This is partially the CI's fault for not running (Travis no longer runs builds for open-source projects), but the CI tests this project with node all the way back to 0.12 (this project is old, and I use it in other projects that are also quite old). This line is invalid in those versions. I probably need to fix the build before accepting more PRs

2021-08-19 12:05 UTC, catdad commented on test/index.test.js
> +    ]).pipe(mod(eol='\r\n')).pipe(es.wait(function (err, data) {
I am not sure about the `mod(eol='\r\n')` bit. This creates a global `eol` variable (since it is not declared) assigns it, and then passes it to the `mod` function? That seems unnecessary (and also, why create a global for no reason?). Seems like we should just do `mod('\r\n')`.

2021-08-19 16:14 UTC, btimby commented on test/index.test.js
> +    ]).pipe(mod(eol='\r\n')).pipe(es.wait(function (err, data) {
You're right. I am more used to Python than Javascript, this is a syntax error on my part.

2021-08-19 16:15 UTC, btimby commented on index.js
> +module.exports = function lfcrClean(eol='\n') {
I will eliminate this syntax. No problem.

2021-08-19 16:22 UTC, btimby commented
The simplification I refer to is in two forms.

 1. I combined the various regular expressions into one. The regex `/\r\n|\n\r|\r|\n/g` will match any sequence of line ending chars. In the order specified within the expression. Thus `\r\n` will match before the individual `\r` and `\n`. This eliminates checking for these sequences individually (basically, I let the regex engine do the same thing).
 2. I modified the way a trailing CRLF is handled on previous chunk. Rather than remembering if it is a CR or LF, I simply carry it over to the next chunk. I use the end callback in `through` to emit this carryover after the final chunk.

2021-08-19 16:23 UTC, btimby commented
As far as why, I am always looking for ways to remove lines of code, as lines of code have bugs, less code, less bugs.

2021-08-20 13:55 UTC, catdad commented
I updated the build so that it once again is running. Please take a look at the failures above. Some are due to issues I already mentioned in the review.

2021-08-20 14:06 UTC, btimby commented
I thought I had pushed those fixes yesterday when I replied. Either I forgot or it failed for some reason. In any case, they are pushed now.

2021-09-01 23:12 UTC, catdad approved these changes

2021-09-01 23:13 UTC, catdad commented
Sorry for the delay, I got super distracted. I made some additional changes and fixed some additional issues, and this looks good now. Thanks for adding this feature!

2021-09-01 23:13 UTC, merged

2021-09-01 23:51 UTC, catdad commented
Unfortunately, I actually had to revert this. I found out after I merged it that it does have a bug in it and does not allow for the same functionality as the previous implementation.

The bug is in this line:

```js
var endCrlf = /\r|\n$/;
```

This regular expression checks for a `\r` anywhere in the string or a `\n` at the end of the string. This can help illustrate that:

![image](https://user-images.githubusercontent.com/2205537/131759728-b1d1a40f-c9fe-4b4a-a57d-3f0473847402.png)

The previous code included behavior when either is at the end. Looking at code coverage, you can see that the `else` in that check is not covered. When I change the expression to match both being at the end (either `/(\r|\n)$/` or `/\r$|\n$/`), all the tests time out and the stream never completes.

I didn't have time to investigate what the issue is. If you want, feel free to recreate this PR and fix the issue.

I guess if nothing else, we both learned that less code can have more bugs 😉.

2021-09-02 02:17 UTC, btimby commented
I made a new PR. I don't think I learned anything of the sort. The solution was to REMOVE CODE ;-)